# Generated by Django 6.0.4 on 2026-04-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='merge_group',
            field=models.CharField(blank=True, default=None, help_text='Leave blank for no sharing. Courses with the same value share a room.', max_length=100, null=True),
        ),
    ]
