# Generated by Django 6.0.4 on 2026-04-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_course_code_unique_per_programme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['programme', 'study_year', 'semester', 'code', 'section']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'programme', 'section')},
        ),
    ]
