# Generated by Django 6.0.4 on 2026-04-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_course_section_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_room_timeslot',
        ),
    ]
